//
// DO NOT EDIT
//
// Generated by swift-atproto
//
// swift-format-ignore-file

import SwiftAtproto

public enum UnknownATPValue: UnknownATPValueProtocol {
  case record(any ATProtoRecord)
  case any(any Codable & Hashable & Sendable)

  public static let allTypes: [String: any ATProtoRecord.Type] = [
    "sh.tangled.actor.profile": Sh.Tangled.ActorProfile.self,
    "sh.tangled.feed.comment": Sh.Tangled.FeedComment.self,
    "sh.tangled.feed.reaction": Sh.Tangled.FeedReaction.self,
    "sh.tangled.feed.star": Sh.Tangled.FeedStar.self,
    "sh.tangled.graph.follow": Sh.Tangled.GraphFollow.self,
    "sh.tangled.label.definition": Sh.Tangled.LabelDefinition.self,
    "sh.tangled.label.op": Sh.Tangled.LabelOp.self,
    "sh.tangled.repo": Sh.Tangled.Repo.self,
    "sh.tangled.repo.artifact": Sh.Tangled.RepoArtifact.self,
    "sh.tangled.repo.issue": Sh.Tangled.RepoIssue.self,
    "sh.tangled.repo.issue.state": Sh.Tangled.Repo.IssueState.self,
    "sh.tangled.repo.pull": Sh.Tangled.RepoPull.self,
    "sh.tangled.repo.pull.status": Sh.Tangled.Repo.PullStatus.self,
  ]

  public var type: Swift.String? {
    switch self {
    case .record(let record):
      return Swift.type(of: record).nsId
    case .any:
      return nil
    }
  }

  public var val: any Codable & Hashable & Sendable {
    switch self {
    case .record(let record):
      record
    case .any(let object):
      object
    }
  }
}
